[workspace]
resolver = "2"
members = [
]

exclude = [

]

[workspace.package]
version = "0.1.0"
edition = "2024"
authors = ["The NewHorizon Kernel Project"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/alessioMaroni/NewHorizon"

[workspace.dependencies]

[package]
name = "NewHorizon-kernel"
version = "0.7.6"
authors.workspace = true
license.workspace = true
repository.workspace = true
edition.workspace = true
description = " "
readme = "README.md"

[dependencies]
uefi = "0.39.0"

[features]

[profile.dev]
opt-level = 0
debug = 2
overflow-checks = true 
debug-assertions = true
lto = false
panic = "abort"

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
panic = "abort"
overflow-checks = true
debug = false
strip = "symbols"
